swagger: "2.0"
info:
  version: 0.1.0
  title: wayfarer
  description: Wayfarer is a public bus transportation booking server
basePath: /api/v1

tags:
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
  /:
    get:
      tags:
        - Home Page
      responses:
        200:
          description: Get Home Page
  /signup:
    post:
      tags:
      - User
      summary: Create a new user
      description: ''
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: user
        description: '' 
        schema:
          type: object
          properties:
            email:
              type: string
            firstName:
              type: string
            lastName:
              type: string
            password:
              type: string
      responses:
        201:
          description: Created
        400:
          description: Bad Request